apiVersion: v1
kind: Service
metadata:
  name: {{ include "fundora.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fundora.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fundora.name" . }}
    app.kubernetes.io/component: app
